Added switching to resolution after successfully creating it (addresolution script).

diff --git a/scripts/addresolution b/scripts/addresolution
--- a/scripts/addresolution
+++ b/scripts/addresolution
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 showExample() { 
-    echo -e "\ne.g. \""$(basename -- "$0")" 1920 1080 60\"\n"
+    echo -e "\ne.g. \""$(basename -- "$0")" eDP1 1920 1080 60\"\n"
 }
 
 createRes() {
@@ -9,32 +9,43 @@ createRes() {
 }
 
 addRes() {
-    xrandr --addmode eDP1 "$WIDTH"x"$HEIGHT"_"$REFRESH".00
+    xrandr --addmode "$DEVICE" "$WIDTH"x"$HEIGHT"_"$REFRESH".00
+}
+
+switchRes() {
+    xrandr --output "$DEVICE" --mode "$WIDTH"x"$HEIGHT"_"$REFRESH".00
 }
 
 # check arguments
 if [ -z "$1" ]; then
-    echo "Please provide a screen width as the first argument"
+    echo "Please provide an output devide as the first argument"
     showExample
     exit 128
 fi
 
 if [ -z "$2" ]; then
-    echo "Please provide a screen height as the second argument"
+    echo "Please provide a screen width as the second argument"
     showExample
     exit 128
 fi
 
 if [ -z "$3" ]; then
-    echo "Please provide a refresh rate as the third argument"
+    echo "Please provide a screen height as the third argument"
+    showExample
+    exit 128
+fi
+
+if [ -z "$4" ]; then
+    echo "Please provide a refresh rate as the fourth argument"
     showExample
     exit 128
 fi
 
 #init
-WIDTH=$1
-HEIGHT=$2
-REFRESH=$3
+DEVICE=$1
+WIDTH=$2
+HEIGHT=$3
+REFRESH=$4
 
 createRes || {
     echo -e "\nERROR creating resolution with \"cvt\"\n"
@@ -45,5 +56,18 @@ addRes || {
     echo -e "\nERROR adding resolution with \"xrandr\"\n"
     exit 1
 }
+
+echo -e "\n"
+while true; do
+    read -p "Do you want to switch to this resolution now? (y/n) " yn
+    case $yn in
+        [Yy]* ) switchRes || {
+                    echo -e "\nERROR switching resolution with \"xrandr\"\n"
+                    return 1
+                }; break;;
+        [Nn]* ) break;;
+        * ) echo "Please type \"y\" or \"n\"";;
+    esac
+done
 
 exit 0
